import assert from 'node:assert/strict';

export async function qualifyFinancial(page, origin) {
  await page.goto(`${origin}/editor`);
  const panel = page.getByRole('region', { name: 'Financial ledger' });
  await panel.getByText('All nominal values are unconfigured.', { exact: true }).waitFor();
  await panel.getByText('3 contributions; page starting at 1.', { exact: true }).waitFor();
  let ledger = await (await fetch(`${origin}/api/financial/ledger`)).json();
  const bits = ledger.items.find(row => row.nativeEventId === 'browser-bits');
  const donation = ledger.items.find(row => row.nativeEventId === 'browser-donation');
  assert.equal(bits.usdAmountMinor, null);
  assert.equal(donation.usdAmountMinor, '1250');
  assert.notEqual(bits.supporterId, donation.supporterId, 'Same display name cannot merge platform identities');
  await panel.getByLabel('Financial timezone').fill('America/Chicago');
  await panel.getByLabel('Current stream start').fill('2026-01-05T12:00:00Z');
  await panel.getByRole('button', { name: 'Save financial periods', exact: true }).click();
  await panel.getByText('Financial periods saved.', { exact: true }).waitFor();
  const settings = await (await fetch(`${origin}/api/financial/settings`)).json();
  assert.equal(settings.timeZone, 'America/Chicago');
  assert.equal(Date.parse(settings.currentStreamStartUtc), Date.parse('2026-01-05T12:00:00Z'));
  await panel.getByLabel('USD per unit').fill('0.0125');
  await panel.getByRole('button', { name: 'Save nominal value', exact: true }).click();
  await panel.getByText('Nominal value saved; history is unchanged.', { exact: true }).waitFor();
  let rules = await (await fetch(`${origin}/api/financial/rules`)).json();
  assert.equal(rules[0].usdMinorPerUnit, '1.25');
  ledger = await (await fetch(`${origin}/api/financial/ledger`)).json();
  assert.equal(ledger.items.find(row => row.id === bits.id).usdAmountMinor, null, 'Rule edits cannot reprice accepted history');
  await panel.getByLabel(`Select contribution ${bits.id}`).check();
  await panel.getByRole('button', { name: 'Reconcile selected valuations', exact: true }).click();
  await panel.getByText('Reconciliation outcomes: reconciled', { exact: true }).waitFor();
  ledger = await (await fetch(`${origin}/api/financial/ledger`)).json();
  assert.equal(ledger.items.find(row => row.id === bits.id).usdAmountMinor, '125');
  const identities = await (await fetch(`${origin}/api/financial/identities`)).json();
  const twitch = identities.find(row => row.platform === 'twitch');
  const kofi = identities.find(row => row.platform === 'kofi');
  await panel.getByLabel('Identity to move').selectOption(twitch.id);
  await panel.getByLabel('Link to supporter').selectOption(kofi.supporterId);
  await panel.getByRole('button', { name: 'Link identity', exact: true }).click();
  await panel.getByText('Identity linked; supporter totals refreshed.', { exact: true }).waitFor();
  const linked = await (await fetch(`${origin}/api/financial/totals?period=all-time`)).json();
  assert.equal(linked.supporters.find(row => row.supporterId === kofi.supporterId).usdAmountMinor, '1375');
  await panel.getByRole('button', { name: 'Unlink identity', exact: true }).click();
  await panel.getByText('Identity separated; supporter totals refreshed.', { exact: true }).waitFor();
  const separate = await (await fetch(`${origin}/api/financial/identities`)).json();
  assert.notEqual(separate.find(row => row.id === twitch.id).supporterId, kofi.supporterId);
  await panel.getByLabel('Rate date').fill('2026-01-05');
  await panel.getByLabel('Manual USD rate').fill('1.23456789');
  await panel.getByRole('button', { name: 'Save manual rate', exact: true }).click();
  await panel.getByText('Dated manual rate saved; history is unchanged.', { exact: true }).waitFor();
  const rates = await (await fetch(`${origin}/api/financial/rates`)).json();
  assert.equal(rates[0].usdPerNativeUnit, '1.23456789');
  await page.reload();
  await panel.getByText(/Saved timezone: America\/Chicago/).waitFor();
  await panel.getByRole('button', { name: 'Remove twitch bits', exact: true }).click();
  await panel.getByText('Rule removed; future values are unconfigured.', { exact: true }).waitFor();
  rules = await (await fetch(`${origin}/api/financial/rules`)).json();
  assert.equal(rules[0].enabled, false);
  await panel.getByRole('button', { name: 'Remove EUR override for 2026-01-05', exact: true }).click();
  await panel.getByText('Manual override removed; history is unchanged.', { exact: true }).waitFor();
  await panel.getByLabel('Totals period').selectOption('custom');
  await panel.getByLabel('Start date', { exact: true }).fill('2026-01-01');
  await panel.getByLabel('End date (exclusive)').fill('2026-02-01');
  await panel.getByText(/Timezone: America\/Chicago/).waitFor();
  assert.equal(await panel.getByRole('button', { name: 'Reconcile selected valuations' }).isDisabled(), true);
  console.log('G07 isolated browser ledger/reconciliation/identity/settings/rule/manual-FX precision and reload qualification passed');
}
