// <auto-generated />
using System;
using ExtensionSuite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExtensionSuite.Data.Migrations
{
    [DbContext(typeof(FoundationDbContext))]
    [Migration("20261002060606_AutomationQueueGroups")]
    partial class AutomationQueueGroups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ExtensionSuite.Data.AutomationEventInbox", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Processed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Sequence");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("Processed", "Sequence");

                    b.ToTable("AutomationInbox");
                });

            modelBuilder.Entity("ExtensionSuite.Data.AutomationExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ActionOrder")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<long>("DueAtTicks")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QueueGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtTicks");

                    b.HasIndex("QueueGroup", "State");

                    b.HasIndex("State", "DueAtTicks");

                    b.HasIndex("EventId", "RuleId", "ActionId")
                        .IsUnique();

                    b.ToTable("AutomationExecutions");
                });

            modelBuilder.Entity("ExtensionSuite.Data.AutomationTemporaryEffect", b =>
                {
                    b.Property<Guid>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAtTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("ActionId");

                    b.HasIndex("State", "ExpiresAtTicks");

                    b.ToTable("AutomationTemporaryEffects");
                });

            modelBuilder.Entity("ExtensionSuite.Data.FinancialAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContributionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContributionId");

                    b.HasIndex("CreatedAtTicks");

                    b.ToTable("FinancialAudits");
                });

            modelBuilder.Entity("ExtensionSuite.Data.FinancialContribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountingState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Estimated")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FxProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("FxRate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FxRateDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GiftCorrelationKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("GiftRole")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("none");

                    b.Property<string>("GiftScopeKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("GiftSenderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("GiftTier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("NativeAmountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NativeCurrency")
                        .HasColumnType("TEXT");

                    b.Property<string>("NativeEventId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NativeMinorUnitDigits")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OccurredAtTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PendingReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SupporterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("UsdAmountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValuationMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("IdentityId");

                    b.HasIndex("OccurredAtTicks");

                    b.HasIndex("Platform");

                    b.HasIndex("SupporterId");

                    b.HasIndex("Platform", "DedupeKey")
                        .IsUnique();

                    b.HasIndex("Platform", "NativeEventId")
                        .IsUnique()
                        .HasFilter("NativeEventId IS NOT NULL");

                    b.HasIndex("StreamId", "OccurredAtTicks");

                    b.HasIndex("Platform", "GiftScopeKey", "GiftCorrelationKey", "GiftRole");

                    b.ToTable("FinancialEvents");
                });

            modelBuilder.Entity("ExtensionSuite.Data.FinancialProjectionReceipt", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ProcessedAtTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.HasIndex("State");

                    b.ToTable("FinancialProjectionReceipts");
                });

            modelBuilder.Entity("ExtensionSuite.Data.GiftAccountingClaim", b =>
                {
                    b.Property<string>("Platform")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyHash")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerContributionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Platform", "KeyHash");

                    b.HasIndex("OwnerContributionId");

                    b.ToTable("GiftAccountingClaims");
                });

            modelBuilder.Entity("ExtensionSuite.Data.OutboxEntry", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtTicks")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeliveredAtTicks")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventId");

                    b.HasIndex("DeliveredAtTicks", "CreatedAtTicks");

                    b.ToTable("Outbox");
                });

            modelBuilder.Entity("ExtensionSuite.Data.RumbleSnapshotState", b =>
                {
                    b.Property<string>("Context")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provenance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Context", "Provenance");

                    b.ToTable("RumbleStates");
                });

            modelBuilder.Entity("ExtensionSuite.Data.RumbleTriggerDelivery", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.HasIndex("State", "CreatedAtTicks");

                    b.ToTable("RumbleDeliveries");
                });

            modelBuilder.Entity("ExtensionSuite.Data.SourceCheckpoint", b =>
                {
                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provenance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Source", "Provenance");

                    b.ToTable("Checkpoints");
                });

            modelBuilder.Entity("ExtensionSuite.Data.StoredAsset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("ExtensionSuite.Data.StoredAutomationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AutomationRules");
                });

            modelBuilder.Entity("ExtensionSuite.Data.StoredConfiguration", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("ExtensionSuite.Data.StoredEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAtTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtTicks");

                    b.HasIndex("Type");

                    b.HasIndex("Source", "Provenance", "DedupeKey")
                        .IsUnique();

                    b.ToTable("Events");
                });

            modelBuilder.Entity("ExtensionSuite.Data.StoredFxRate", b =>
                {
                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestedDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Origin")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Estimated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RateDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsdPerNativeUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Currency", "RequestedDay", "Origin");

                    b.ToTable("FxRates");
                });

            modelBuilder.Entity("ExtensionSuite.Data.StoredLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TimestampTicks")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TimestampTicks");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("ExtensionSuite.Data.StoredOverlay", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Overlays");
                });

            modelBuilder.Entity("ExtensionSuite.Data.StoredOverlayRevision", b =>
                {
                    b.Property<string>("OverlayId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SavedAtTicks")
                        .HasColumnType("INTEGER");

                    b.HasKey("OverlayId", "Version");

                    b.ToTable("OverlayRevisions");
                });

            modelBuilder.Entity("ExtensionSuite.Data.StoredOverlayToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAtTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OverlayId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Revoked")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("OverlayId");

                    b.ToTable("OverlayTokens");
                });

            modelBuilder.Entity("ExtensionSuite.Data.StoredValuationRule", b =>
                {
                    b.Property<string>("Platform")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tier")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("UsdMinorPerUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Platform", "Type", "Tier");

                    b.ToTable("ValuationRules");
                });

            modelBuilder.Entity("ExtensionSuite.Data.Supporter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Supporters");
                });

            modelBuilder.Entity("ExtensionSuite.Data.SupporterIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SupporterId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SupporterId");

                    b.HasIndex("Platform", "IdentityKey")
                        .IsUnique();

                    b.ToTable("SupporterIdentities");
                });

            modelBuilder.Entity("ExtensionSuite.Data.AutomationEventInbox", b =>
                {
                    b.HasOne("ExtensionSuite.Data.StoredEvent", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExtensionSuite.Data.FinancialContribution", b =>
                {
                    b.HasOne("ExtensionSuite.Data.SupporterIdentity", null)
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExtensionSuite.Data.Supporter", null)
                        .WithMany()
                        .HasForeignKey("SupporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ExtensionSuite.Data.FinancialProjectionReceipt", b =>
                {
                    b.HasOne("ExtensionSuite.Data.StoredEvent", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExtensionSuite.Data.GiftAccountingClaim", b =>
                {
                    b.HasOne("ExtensionSuite.Data.FinancialContribution", null)
                        .WithMany()
                        .HasForeignKey("OwnerContributionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ExtensionSuite.Data.OutboxEntry", b =>
                {
                    b.HasOne("ExtensionSuite.Data.StoredEvent", null)
                        .WithOne()
                        .HasForeignKey("ExtensionSuite.Data.OutboxEntry", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExtensionSuite.Data.RumbleTriggerDelivery", b =>
                {
                    b.HasOne("ExtensionSuite.Data.StoredEvent", null)
                        .WithOne()
                        .HasForeignKey("ExtensionSuite.Data.RumbleTriggerDelivery", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExtensionSuite.Data.StoredOverlayRevision", b =>
                {
                    b.HasOne("ExtensionSuite.Data.StoredOverlay", null)
                        .WithMany()
                        .HasForeignKey("OverlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExtensionSuite.Data.StoredOverlayToken", b =>
                {
                    b.HasOne("ExtensionSuite.Data.StoredOverlay", null)
                        .WithMany()
                        .HasForeignKey("OverlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExtensionSuite.Data.SupporterIdentity", b =>
                {
                    b.HasOne("ExtensionSuite.Data.Supporter", null)
                        .WithMany()
                        .HasForeignKey("SupporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
