// <auto-generated />
using System;
using ExtensionSuite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExtensionSuite.Data.Migrations
{
    [DbContext(typeof(FoundationDbContext))]
    [Migration("20261001150413_OverlayRuntime")]
    partial class OverlayRuntime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ExtensionSuite.Data.OutboxEntry", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtTicks")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeliveredAtTicks")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventId");

                    b.HasIndex("DeliveredAtTicks", "CreatedAtTicks");

                    b.ToTable("Outbox");
                });

            modelBuilder.Entity("ExtensionSuite.Data.RumbleSnapshotState", b =>
                {
                    b.Property<string>("Context")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provenance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Context", "Provenance");

                    b.ToTable("RumbleStates");
                });

            modelBuilder.Entity("ExtensionSuite.Data.RumbleTriggerDelivery", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.HasIndex("State", "CreatedAtTicks");

                    b.ToTable("RumbleDeliveries");
                });

            modelBuilder.Entity("ExtensionSuite.Data.SourceCheckpoint", b =>
                {
                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provenance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Source", "Provenance");

                    b.ToTable("Checkpoints");
                });

            modelBuilder.Entity("ExtensionSuite.Data.StoredAsset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("ExtensionSuite.Data.StoredConfiguration", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("ExtensionSuite.Data.StoredEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAtTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtTicks");

                    b.HasIndex("Type");

                    b.HasIndex("Source", "Provenance", "DedupeKey")
                        .IsUnique();

                    b.ToTable("Events");
                });

            modelBuilder.Entity("ExtensionSuite.Data.StoredLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TimestampTicks")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TimestampTicks");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("ExtensionSuite.Data.StoredOverlay", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Overlays");
                });

            modelBuilder.Entity("ExtensionSuite.Data.StoredOverlayToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAtTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OverlayId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Revoked")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("OverlayId");

                    b.ToTable("OverlayTokens");
                });

            modelBuilder.Entity("ExtensionSuite.Data.OutboxEntry", b =>
                {
                    b.HasOne("ExtensionSuite.Data.StoredEvent", null)
                        .WithOne()
                        .HasForeignKey("ExtensionSuite.Data.OutboxEntry", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExtensionSuite.Data.RumbleTriggerDelivery", b =>
                {
                    b.HasOne("ExtensionSuite.Data.StoredEvent", null)
                        .WithOne()
                        .HasForeignKey("ExtensionSuite.Data.RumbleTriggerDelivery", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExtensionSuite.Data.StoredOverlayToken", b =>
                {
                    b.HasOne("ExtensionSuite.Data.StoredOverlay", null)
                        .WithMany()
                        .HasForeignKey("OverlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
