// <auto-generated />
using System;
using ExtensionSuite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExtensionSuite.Data.Migrations
{
    [DbContext(typeof(FoundationDbContext))]
    partial class FoundationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ExtensionSuite.Data.OutboxEntry", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtTicks")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeliveredAtTicks")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventId");

                    b.HasIndex("DeliveredAtTicks", "CreatedAtTicks");

                    b.ToTable("Outbox");
                });

            modelBuilder.Entity("ExtensionSuite.Data.SourceCheckpoint", b =>
                {
                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provenance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Source", "Provenance");

                    b.ToTable("Checkpoints");
                });

            modelBuilder.Entity("ExtensionSuite.Data.StoredEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAtTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtTicks");

                    b.HasIndex("Type");

                    b.HasIndex("Source", "Provenance", "DedupeKey")
                        .IsUnique();

                    b.ToTable("Events");
                });

            modelBuilder.Entity("ExtensionSuite.Data.OutboxEntry", b =>
                {
                    b.HasOne("ExtensionSuite.Data.StoredEvent", null)
                        .WithOne()
                        .HasForeignKey("ExtensionSuite.Data.OutboxEntry", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
