<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <Content Update="wwwroot/**/*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="ExtensionSuite.Host.Tests" />
    <ProjectReference Include="../ExtensionSuite.DesktopControl/ExtensionSuite.DesktopControl.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <ProjectReference Include="../ExtensionSuite.Core/ExtensionSuite.Core.csproj" />
    <ProjectReference Include="../ExtensionSuite.Data/ExtensionSuite.Data.csproj" />
    <ProjectReference Include="../ExtensionSuite.StreamerBot/ExtensionSuite.StreamerBot.csproj" />
    <ProjectReference Include="../ExtensionSuite.Rumble/ExtensionSuite.Rumble.csproj" />
    <ProjectReference Include="../ExtensionSuite.Overlays/ExtensionSuite.Overlays.csproj" />
    <ProjectReference Include="../ExtensionSuite.Finance/ExtensionSuite.Finance.csproj" />
    <ProjectReference Include="../ExtensionSuite.Web/ExtensionSuite.Web.csproj" />
  </ItemGroup>
</Project>
