<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../ExtensionSuite.Core/ExtensionSuite.Core.csproj" />
    <ProjectReference Include="../ExtensionSuite.Data/ExtensionSuite.Data.csproj" />
    <ProjectReference Include="../ExtensionSuite.StreamerBot/ExtensionSuite.StreamerBot.csproj" />
    <ProjectReference Include="../ExtensionSuite.Rumble/ExtensionSuite.Rumble.csproj" />
    <ProjectReference Include="../ExtensionSuite.Overlays/ExtensionSuite.Overlays.csproj" />
    <ProjectReference Include="../ExtensionSuite.Finance/ExtensionSuite.Finance.csproj" />
    <ProjectReference Include="../ExtensionSuite.Web/ExtensionSuite.Web.csproj" />
  </ItemGroup>
</Project>
